name: minitwitter
services:
  load-balancer:
    image: nginx
    container_name: load-balancer
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx.conf.ro

  postgres:
    image: postgres
    container_name: my-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: supersecret123
      POSTGRES_DB: minitwitter
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
  
  minitwitter-frontend:
    container_name: frontend
    restart: always
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      NUX_PubliC_API_BASE_URL: http://localhost:80

  minitwitter1:
    image: wotasoy/simple-api
    container_name: minitwitter1
    restart: always
    environment:
      DATABASE_URL: postgressql://postgres:supersecret123@my-postgres:5432/minitwitter
      command: /bin/sh -c "bunx drizzle-kit push && bun run prod"
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data

  minitwitter2:
    image: wotasoy/simple-api
    container_name: minitwitter2
    restart: always
    environment:
      DATABASE_URL: postgressql://postgres:supersecret123@my-postgres:5432/minitwitter
      command: /bin/sh -c "bunx drizzle-kit push && bun run prod"
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    ports:
      - 12434:11434
    volumes:
      - ./docker-data/ollama:/root/.ollama
    environment:
      - NVIDIA_VISIBLE_DEVICES=1

  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

volumes: 
  ollama: {}
