name: minitwitter
services:
  webserver:
    image: nginx
    container_name: webserver
    restart: always
    ports:
      - 80:80

  postgres:
    image: postgres
    container_name: my-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: supersecret123
      POSTGRES_DB: minitwitter
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data